name: 'Review with AI'

on:
  pull_request:

jobs:
  review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR Diff
        id: get_diff
        run: |
          git diff --full-index ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > pr_diff.txt
          echo "PR_DIFF=$(cat pr_diff.txt)" >> $GITHUB_OUTPUT

      - name: AI Review with OpenAI API
        id: openai_review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PR_DIFF: ${{ steps.get_diff.outputs.PR_DIFF }}
        run: |
          PAYLOAD=$(jq -n \
            --arg pr_diff "$PR_DIFF" \
            '{
              "model": "gpt-4o",
              "messages": [
                {
                  "role": "system",
                  "content": "Please provide the C++ code you would like me to review. I will analyze it for areas of improvement and provide concise suggestions and code examples. I will focus on the following aspects: Code readability, Coding conventions and best practices, Bugs and logical errors, Performance and security. I will omit praise, avoid verbose explanations, and summarize the key points in a bulleted list. Please write your reply in Japanese."
                },
                {
                  "role": "user",
                  "content": "以下に変更されたC++コードの差分を記載します。\nこの内容をレビューしてください。\n```diff\n" + $pr_diff + "\n```"
                }
              ]
            }')

          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            | jq -r '.choices[0].message.content'
          )

          echo "response=$(echo "$RESPONSE" | sed 's/"/\\"/g')" >> $GITHUB_OUTPUT

      - name: Comment on PR
        env:
          RESPONSE: ${{ steps.openai_review.outputs.response }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$RESPONSE" > comment.txt
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.txt