name: 'Review with AI'

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR Diff
        id: get_diff
        run: |
          # git diff の出力を base64 でエンコードして渡す
          PR_DIFF_BASE64=$(git diff --full-index ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | base64 -w 0)
          echo "PR_DIFF=$PR_DIFF_BASE64" >> $GITHUB_OUTPUT

      - name: AI Review with OpenAI API
        id: openai_review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PR_DIFF_BASE64: ${{ steps.get_diff.outputs.PR_DIFF }}
        run: |
          PR_DIFF=$(echo "$PR_DIFF_BASE64" | base64 --decode)
          
          USER_CONTENT=$(printf "以下に変更されたC++コードの差分を記載します。\nこの内容をレビューしてください。\n\`\`\`diff\n%s\n\`\`\`" "$PR_DIFF")
          
          PAYLOAD=$(jq -n \
            --arg user_content "$USER_CONTENT" \
            '{
              "model": "gpt-4o",
              "messages": [
                {
                  "role": "system",
                  "content": "Please provide the C++ code you would like me to review. I will analyze it for areas of improvement and provide concise suggestions and code examples. I will focus on the following aspects: Code readability, Coding conventions and best practices, Bugs and logical errors, Performance and security. I will omit praise, avoid verbose explanations, and summarize the key points in a bulleted list. Please write your reply in Japanese."
                },
                {
                  "role": "user",
                  "content": $user_content
                }
              ]
            }')
          
          # URLを修正
          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            | jq -r '.choices[0].message.content'
          )
          
          # レスポンスをファイルに保存し、ファイル名を次のステップに出力
          echo "$RESPONSE" > response_body.txt
          echo "response_file=response_body.txt" >> $GITHUB_OUTPUT

      - name: Comment on PR
        # このステップでは環境変数(env)は不要
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 前のステップから出力されたファイル名を直接使ってコメントを投稿
          gh pr comment ${{ github.event.pull_request.number }} --body-file ${{ steps.openai_review.outputs.response_file }}